version: '2'

services:
    prometheus:
        image: prom/prometheus:stable
        container_name: monitoring_prometheus
        restart: unless-stopped
        volumes:
          - ./data/prometheus/config:/etc/prometheus/
          - ./data/prometheus/data:/prometheus
        command:
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-storage.local.path=/prometheus'
          - '-alertmanager.url=http://alertmanager:9093'
        expose:
          - 9090
        ports:
          - 9090:9090
        links:
          - cadvisor:cadvisor
          - node-exporter:node-exporter
        networks:
            - things-board_default

    node-exporter:
        image: prom/node-exporter:stable
        container_name: monitoring_node_exporter
        restart: unless-stopped
        expose:
          - 9100
        networks:
            - things-board_default

    cadvisor:
        image: google/cadvisor:stable
        container_name: monitoring_cadvisor
        restart: unless-stopped
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        expose:
          - 8080
        networks:
            - things-board_default

    grafana:
        image: grafana/grafana:stable
        container_name: monitoring_grafana
        restart: unless-stopped
        links:
          - prometheus:prometheus
        volumes:
          - ./data/grafana:/var/lib/grafana
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
          - GF_USERS_ALLOW_SIGN_UP=false
          - GF_SERVER_DOMAIN=myrul.com
          - GF_SMTP_ENABLED=true
          - GF_SMTP_HOST=smtp.gmail.com:587
          - GF_SMTP_USER=myadrress@gmail.com
          - GF_SMTP_PASSWORD=mypassword
          - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
        networks:
            - things-board_default
